export const metadata = {
    title: 'Add Item | Next Hero',
    description: 'Generated by create next app',
}

const AddItemPage = () => {
    return (
        <div>
            Add Items
        </div>
    );
};

export default AddItemPage;