export const metadata = {
    title: 'Manage Items | Next Hero',
    description: 'Generated by create next app',
}

const ManageItemsPage = () => {
    return (
        <div>
            Manage Items
        </div>
    );
};

export default ManageItemsPage;