export const metadata = {
    title: 'Profile | Next Hero',
    description: 'Generated by create next app',
}

const profilePage = () => {
    return (
        <div>
            <h1>Profile page</h1>
        </div>
    );
};

export default profilePage;