export const metadata = {
    title: 'Dashboard | Next Hero',
    description: 'Generated by create next app',
}
const dashboardPage = () => {
    return (
        <div>
            Dashboard
        </div>
    );
};

export default dashboardPage;